update version and various small changes

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,8 +1,12 @@
 #! /bin/bash
-# This script is meant to evoke the algorithm without requiring any input arguments
+#
+#
 #
 
-# Define directory names and containers
+
+################################################################################
+# DEFINE VARIABLES
+
 FLYWHEEL_BASE=/flywheel/v0
 MANIFEST_FILE=$FLYWHEEL_BASE/manifest.json
 CONFIG_FILE=$FLYWHEEL_BASE/config.json
@@ -12,8 +16,23 @@ OUTPUT_DIR=$ROOTOUT_DIR/out
 WORKING_DIR=$ROOTOUT_DIR/work
 CONTAINER='[flywheel/mriqc]'
 
-# Configure the ENV according to the original Docker image
+
+################################################################################
+# CONFIGURE ENV
+
 source ${FLYWHEEL_BASE}/docker-env.sh
+source /etc/fsl/fsl.sh
+source /etc/afni/afni.sh
+
+
+################################################################################
+# LOGGING
+
+# exec > >(tee -i $FLYWHEEL/output/stdout.log) 2> >(tee -i $FLYWHEEL/output/stderr.log >&2)
+
+
+################################################################################
+# VALIDATE INPUT DATA
 
 # Check if the input directory is not empty
 if [[ "$(ls -A $INPUT_DIR)" ]] ; then
@@ -28,25 +47,33 @@ input_file=`find $INPUT_DIR -iname '*.nii' -o -iname '*.nii.gz'`
 bni=`basename "$input_file"`
 filename="${bni%%.*}"
 inextension="${bni#*.}"
+
 # If input file not found, raise error
 if [[ ! -e $input_file ]]; then
     echo "No Nifti files (.nii or .nii.gz) were found within input directory $INPUT_DIR"
     exit 1
 fi
 
-## Check if the input filename is already BIDS compliant
+
+################################################################################
+## CHECK FOR BIDS COMPLIANCE
+
 bids_func_re="sub-[0-9a-zA-Z]+_task-[0-9a-zA-Z]+(_acq-[0-9a-zA-Z]+)?(_rec-[0-9a-zA-Z]+)?(_run-[0-9]+)?_bold"
 bids_anat_re="sub-[0-9a-zA-Z]+(_ses-[0-9a-zA-Z]+)?(_acq-[0-9a-zA-Z]+)?(_rec-[0-9a-zA-Z]+)?(_run-[0-9]+)?_[T1w|T2w]"
+
 if [[ $filename =~ $bids_func_re ]]; then
     bids_compliant=true
     measurement="Functional"
+
 elif [[ $filename =~ $bids_anat_re ]]; then
     bids_compliant=true
     # measurement is either T1w or T2w
     measurement="${filename:(-3)}"
-# Otherwise, not BIDS compliant -- need to determine measurement (Functional or Structural) from config file
+
 else
+    # Not BIDS compliant -- need to determine measurement (Functional or Structural) from config file
     bids_compliant=false
+
     # Check config file for measurement
     if [[ -e $CONFIG_FILE ]]; then
         measurement=`cat $CONFIG_FILE | jq -r '.config.measurement'`
@@ -55,6 +82,7 @@ else
         measurement=`cat $MANIFEST_FILE | jq -r '.config.measurement.default'`
     fi
 fi
+
 # Define BIDS subdirectory based on measurement type
 if [[ $measurement = 'Functional' ]]; then
     subdirname='func'
@@ -62,7 +90,10 @@ else
     subdirname='anat'
 fi
 
-# Define BIDS features based on spec
+
+################################################################################
+# DEFINE BIDS FEATURES BASED ON SPEC
+
 if [[ $bids_compliant = 'true' ]]; then
     # Since BIDS compliant -- extract the participant label number and description of the file
     #   participant label to be used in naming scheme as well as being passed to algorithm as a command line argument
@@ -82,22 +113,31 @@ else
     fi
 fi
 
-## Create a BIDS format directory to be ingested by MRIQC
+
+################################################################################
+# CREATE A BIDS FORMATTED DIRECTORY
+
 # Define top level dir
 BIDS_DIR=$WORKING_DIR/sub-$PARTICIPANT_LABEL
+
 # Define subdir and bids_file
 BIDS_SUBDIR=$BIDS_DIR/$subdirname
 bids_file=sub-$PARTICIPANT_LABEL$filedesc.$inextension
 mkdir -p $BIDS_SUBDIR
+
 # Change filename to be in BIDS format (may already be in BIDS format)
 cp $input_file $BIDS_SUBDIR/$bids_file
 
-# Call MRIQC software
-source /etc/fsl/fsl.sh
-source /etc/afni/afni.sh
+
+################################################################################
+# RUN MRIQC
+
 /usr/local/miniconda/bin/mriqc $BIDS_DIR $OUTPUT_DIR participant -w $WORKING_DIR --participant_label $PARTICIPANT_LABEL
 
-# Cleanup outputs
+
+################################################################################
+# CLEANUP OUTPUTS & GENERATE METADATA
+
 # Define the expected output report filename generated by mriqc - NOTE: strange case with Functional file desc
 if [[ $filedesc == "_task-_bold" ]]; then
     outfilename=sub-$PARTICIPANT_LABEL'_bold.html'
@@ -107,6 +147,7 @@ fi
 
 # Move html report to the output directory and rename to match the original input filename
 cp $OUTPUT_DIR/reports/$outfilename $ROOTOUT_DIR/$filename'_mriqc.qa.html'
+
 # Remove the working directory
 rm -r $WORKING_DIR
 rm -r $OUTPUT_DIR
@@ -119,6 +160,7 @@ if [[ -z $outputs ]]
         echo "No results found in output directory... Exiting"
         exit 1
     else
+        # Metadata Creation
         echo -e "{ \"acquisition\" : { \"files\" : [{ \"name\" : \""$filename'_mriqc.qa.html'"\", \"type\": \"qa\", \"measurements\": [\""$measurement"\"]}]}}" > $ROOTOUT_DIR/.metadata.json
         chmod -R 777 $ROOTOUT_DIR
         echo -e "Wrote: `ls $ROOTOUT_DIR`"
