Add optional config to save all outputs #14

diff --git a/run b/run
--- a/run
+++ b/run
@@ -6,7 +6,6 @@
 #
 #
 
-
 ################################################################################
 # DEFINE VARIABLES
 
@@ -19,7 +18,6 @@ OUTPUT_DIR=$ROOTOUT_DIR/out
 WORKING_DIR=$ROOTOUT_DIR/work
 CONTAINER='[flywheel/mriqc]'
 
-
 ################################################################################
 # CONFIGURE ENV
 
@@ -27,12 +25,20 @@ source ${FLYWHEEL_BASE}/docker-env.sh
 source /etc/fsl/fsl.sh
 source /etc/afni/afni.sh
 
-
 ################################################################################
 # LOGGING
 
 # exec > >(tee -i $FLYWHEEL/output/stdout.log) 2> >(tee -i $FLYWHEEL/output/stderr.log >&2)
 
+##############################################################################
+# Parse configuration
+
+if [[ -f $CONFIG_FILE ]]; then
+  eval $(jq -r '.config | to_entries[] | "config_\(.key)=\(.value)"' $CONFIG_FILE)
+else
+  CONFIG_FILE=$FLYWHEEL_BASE/manifest.json
+  eval $(jq -r '.config | to_entries[] | "config_\(.key)=\(.value.default)"' $CONFIG_FILE)
+fi
 
 ################################################################################
 # VALIDATE INPUT DATA
@@ -66,8 +72,8 @@ bids_anat_re="sub-[0-9a-zA-Z]+(_ses-[0-9a-zA-Z]+)?(_acq-[0-9a-zA-Z]+)?(_ce-[0-9a
 
 if [[ $filename =~ $bids_func_re ]]; then
     bids_compliant=true
-    measurement="functional"
-    echo "Input filename is in BIDS format for a $measurement image"
+    config_measurement="functional"
+    echo "Input filename is in BIDS format for a $config_measurement image"
 
 elif [[ $filename =~ $bids_anat_re ]]; then
     bids_compliant=true
@@ -76,56 +82,49 @@ elif [[ $filename =~ $bids_anat_re ]]; then
     # Transform T1w/T2w -> anatomy_t1w/anatomy_t2w
     desc="${filename:(-3)}"
     if [[ $desc = 'T1w' ]]; then
-        measurement='anatomy_t1w'
+        config_measurement='anatomy_t1w'
     fi
     if [[ $desc = 'T2w' ]]; then
-        measurement='anatomy_t2w'
+        config_measurement='anatomy_t2w'
     fi
-    echo "Input filename is in BIDS format for an $measurement image"
+    echo "Input filename is in BIDS format for an $config_measurement image"
 
 else
     # Not BIDS compliant -- need to determine measurement (functional, anatomy_t1w, or anatomy_t2w) from config file
     bids_compliant=false
     echo "Input filename is not in BIDS format. Detecting measurement..."
-
-    # Check config file for measurement
-    if [[ -e $CONFIG_FILE ]]; then
-        measurement=`cat $CONFIG_FILE | jq -r '.config.measurement'`
-        # Make measurement all lowercase
-        measurement=`echo ${measurement} | tr '[:upper:]' '[:lower:]'`
-    # If no config file present, get default from manifest file
-    else
-        measurement=`cat $MANIFEST_FILE | jq -r '.config.measurement.default'`
-    fi
+    # Using measurment read from config or manifest
+    #   Make measurement all lowercase
+    config_measurement=`echo ${config_measurement} | tr '[:upper:]' '[:lower:]'`
 
     ## Determine measurement
     # Check if autodetect, otherwise use what was read in from config.json/manifest.json
-    if [[ $measurement = 'auto-detect' ]]; then
+    if [[ $config_measurement = 'auto-detect' ]]; then
         echo "Auto-detecting input file measurement"
         # Get measurement from context
-        measurement=`cat $CONFIG_FILE | jq -r '.inputs.nifti.object.measurements[0]'`
+        config_measurement=`cat $CONFIG_FILE | jq -r '.inputs.nifti.object.measurements[0]'`
         # Make measurement all lowercase
-        measurement=`echo ${measurement} | tr '[:upper:]' '[:lower:]'`
+        config_measurement=`echo ${config_measurement} | tr '[:upper:]' '[:lower:]'`
         # Check if measurement that is read in is either anatomy_t1w, anatomy_t2w, or functional
         measurementArray=(functional anatomy_t1w anatomy_t2w)
         # Determine if measurement
         found=false
         for item in "${measurementArray[@]}"; do
-            if [[ $measurement == $item ]]; then
+            if [[ $config_measurement == $item ]]; then
                 found=true
             fi
         done
         if $found; then
-            echo "Auto-detected input file measurement as $measurement"
+            echo "Auto-detected input file measurement as $config_measurement"
         else
-            echo "Auto-detected measurement is $measurement"
+            echo "Auto-detected measurement is $config_measurement"
             echo "Measurement needs to be 'anatomy_t1w', 'anatomy_t2w', or 'functional'"
             echo "MRIQC algorithm will not run - nothing to do - exit(0)"
             exit 0
         fi
     else
     # Not auto-detecting measurement - measurement what was given by user
-        echo "File measurement indicated by user. Measurement is $measurement"
+        echo "File measurement indicated by user. Measurement is $config_measurement"
     fi
 fi
 
@@ -133,9 +132,9 @@ fi
 # DEFINE BIDS LABELS
 
 # Define BIDS subdirectory based on measurement type
-if [[ "$measurement" = 'anatomy_t1w' ]]; then
+if [[ "$config_measurement" = 'anatomy_t1w' ]]; then
     subdirname='anat'
-elif [[ "$measurement" = 'anatomy_t2w' ]]; then
+elif [[ "$config_measurement" = 'anatomy_t2w' ]]; then
     subdirname='anat'
 else
     subdirname='func'
@@ -152,16 +151,16 @@ else
     # Since NOT BIDS compliant-- extract all letters and numbers from input filename to be used as participant label
     PARTICIPANT_LABEL="${filename//[!0-9a-zA-Z]}"
     # Determine the file description at the end of the filename
-    if [[ $measurement = "functional" ]]; then
+    if [[ $config_measurement = "functional" ]]; then
         # Make the file description the most basic form in BIDS format for functional images
         filedesc='_task-_bold'
     else
         # The file description is T1w if measurement is 'anatomy_t1w'
-        if [[ $measurement == "anatomy_t1w" ]]; then
+        if [[ $config_measurement == "anatomy_t1w" ]]; then
             filedesc='_T1w'
         fi
         # The file description is T2w if measurement is 'anatomy_t2w'
-        if [[ $measurement == "anatomy_t2w" ]]; then
+        if [[ $config_measurement == "anatomy_t2w" ]]; then
             filedesc='_T2w'
         fi
     fi
@@ -186,7 +185,9 @@ cp "$input_file" $BIDS_SUBDIR/$bids_file
 ################################################################################
 # RUN MRIQC
 
-/usr/local/miniconda/bin/mriqc $BIDS_DIR $OUTPUT_DIR participant -w $WORKING_DIR --participant_label $PARTICIPANT_LABEL
+time /usr/local/miniconda/bin/mriqc $BIDS_DIR $OUTPUT_DIR participant -w $WORKING_DIR --participant_label $PARTICIPANT_LABEL
+MRIQC_EXITSTATUS=$?
+
 
 ################################################################################
 # CLEANUP OUTPUTS & GENERATE METADATA
@@ -198,10 +199,28 @@ else
     outfilename=sub-$PARTICIPANT_LABEL$filedesc'.html'
 fi
 
-# Move html report to the output directory and rename to match the original input filename
-cp "$OUTPUT_DIR"/reports/"$outfilename" "$ROOTOUT_DIR"/"$filename"'_mriqc.qa.html'
+# Check if MRIQC succeeded
+if [[ $MRIQC_EXITSTATUS == 0 ]]; then
+  # Define report and zip filename
+  report_filename="$filename"_mriqc.qa.html
+  zip_filename="$filename"_mriqc_output
+  # Check if save outputs config present, if so zip up all outputs
+  if [ $config_save_outputs == 'true' ]; then
+    # Generate zipped output of mriqc
+    cd "$ROOTOUT_DIR"
+    zip -r "$ROOTOUT_DIR"/"$zip_filename" *
+    # Metadata Creation - for the report and zipfile
+    echo -e "{ \"acquisition\" : { \"files\" : [{ \"name\" : \""$report_filename"\", \"type\": \"qa\", \"measurements\": [\""$config_measurement"\"]},
+            { \"name\" : \""$zip_filename".zip\", \"type\": \"qa\", \"measurements\": [\""$config_measurement"\"]}]}}" > $ROOTOUT_DIR/.metadata.json
+  else
+    # Metadata Creation - for the single report
+    echo -e "{ \"acquisition\" : { \"files\" : [{ \"name\" : \""$report_filename"\", \"type\": \"qa\", \"measurements\": [\""$config_measurement"\"]}]}}" > $ROOTOUT_DIR/.metadata.json
+  fi
+  # Move html report to the output directory and rename to match the original input filename
+  cp "$OUTPUT_DIR"/reports/"$outfilename" "$ROOTOUT_DIR"/"$report_filename"
+fi
 
-# Remove the working directory
+# Cleanup
 rm -r $WORKING_DIR
 rm -r $OUTPUT_DIR
 
@@ -209,14 +228,12 @@ rm -r $OUTPUT_DIR
 outputs=`find $ROOTOUT_DIR -type f -name "*"`
 # If outputs exist, then go on...
 if [[ -z $outputs ]]
-    then
-        echo "No results found in output directory... Exiting"
-        exit 1
-    else
-        # Metadata Creation
-        echo -e "{ \"acquisition\" : { \"files\" : [{ \"name\" : \""$filename'_mriqc.qa.html'"\", \"type\": \"qa\", \"measurements\": [\""$measurement"\"]}]}}" > $ROOTOUT_DIR/.metadata.json
-        chmod -R 777 $ROOTOUT_DIR
-        echo -e "Wrote: `ls $ROOTOUT_DIR`"
+  then
+    echo "No results found in output directory... Exiting"
+    exit 1
+  else
+    chmod -R 777 $ROOTOUT_DIR
+    echo -e "Wrote: `ls $ROOTOUT_DIR`"
 fi
 
-exit 0
+exit $MRIQC_EXITSTATUS
